INSERT INTO food (name, description, price, image URL)
VALUES ('Perogy', 'Fried perogies, double-smoked bacon, sour cream. 1450 CAL', $12.99, public/images/Perogy-Poutine.png)
INSERT INTO food (name, description, price, image URL)
VALUES ('PopCorn Chicken''Fresh hand cut fries, cheese curd, signature gravy, popcorn chicken. 1230 CAL', $12.99, public/images/popcorn-chicken.png)
INSERT INTO food (name, description, price, image URL)
VALUES ('Butter Chicken', 'Grilled chicken, butter chicken sauce, green onions. 1350 CAL, $12.99', public/images/ButterChicken.png)
INSERT INTO food (name, description, price, image URL)
VALUES ('Avalance', 'Fresh hand-cut French fries, Smoke’s Signature Gravy, Quebec cheese curds, chipotle pulled pork, grilled chicken, double-smoked bacon, and ranch. 1650 CAL, $15.99', public/images/Avalanche_Poutine-thumb.png)
